spring:
  application:
    name: PaymentTest
  datasource:
    url: jdbc:h2:./db/main;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
