spring:
  application:
    name: PaymentTest
  datasource:
    url: jdbc:h2:./db/main;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
token:
  signing:
    key: 871228f50bce8e0f64a0a5ae486f697ccc6690ac1d13c1971b84b368abb048b6

